version: "3.6"


services:

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: typo3
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --skip-character-set-client-handshake
    restart: always

  web:
    build: .
    ports:
      - 80:80
    volumes:
      - fileadmin:/var/www/html/fileadmin:delegated
      - typo3conf:/var/www/html/typo3conf:delegated
      - uploads:/var/www/html/uploads:delegated
    #command: sh /var/www/html/fileadmin/install.sh
    links:
      - db

  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - db
    restart: always

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    links:
#      - db
#    ports:
#      - 8080:8080
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#    restart: always

volumes:
  fileadmin:
  typo3conf:
  uploads:
