version: "3.6"

services:

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: typo3
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --skip-character-set-client-handshake
    restart: always

  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - db
    restart: always
    depends_on:
      - db

  web:
    build:
      context: ./Builds/apache2
    ports:
      - 80:80
    volumes:
      - ./Volumes/fileadmin:/var/www/html/fileadmin
      - ./Volumes/typo3conf:/var/www/html/typo3conf
      - ./Volumes/typo3temp:/var/www/html/typo3temp
      - ./Volumes/uploads:/var/www/html/uploads
    links:
      - db
    depends_on:
      - db

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    links:
#      - db
#    ports:
#      - 8080:8080
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#    restart: always

#volumes:

